import java.io.*;
class FileWriterDemo 
{
	public static void main(String[] args) throws IOException
	{
			FileWriter fw=new FileWriter("FileWriterDemo.txt");
			fw.write(97);
			fw.write('\n');
			fw.write(98);
			fw.write('\n');
			fw.write(99);
			fw.write('\n');
			fw.write(100);
			fw.write('\n');
			fw.write(101);
			fw.write('\n');
			fw.write(102);
			fw.write('\n');
			fw.write(103);
			fw.write('\n');
			fw.write(104);
			fw.write('\n');
			fw.write(105);
			fw.write('\n');
			fw.write(106);
			fw.write('\n');
			fw.write(107);
			fw.write('\n');
			fw.write(108);
			fw.write('\n');
			fw.write(109);
			fw.write('\n');
			fw.write(110);
			fw.write('\n');
			fw.write(111);
			fw.write('\n');
			fw.write(112);
			fw.write('\n');
			fw.write(113);
			fw.write('\n');
			fw.write(114);
			fw.write('\n');
			fw.write(115);
			fw.write('\n');
			fw.write(116);
			fw.write('\n');
			fw.write(117);
			fw.write('\n');
			fw.write('v');
			fw.write('\n');
			fw.write("praneeeth");
			fw.flush();	
	}
}
